# Generated by Django 4.0.2 on 2022-02-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
