# Generated by Django 4.0.2 on 2022-02-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
