# Generated by Django 4.0.2 on 2022-02-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_commit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='api.commit'),
        ),
    ]
